
package aminParsian.webService.AchAmin.ir.parsian_bank;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import aminParsian.webService.AchAmin.com.caspian.channelmanager.core.webservicegateway.endpoint.corebankingservice.*;
import aminParsian.webService.AchAmin.com.caspian.channelmanager.core.webservicegateway.service.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ParsianBankSoap", targetNamespace = "http://www.parsian-bank.ir/")
@XmlSeeAlso({
    aminParsian.webService.AchAmin.com.caspian.channelmanager.core.webservicegateway.endpoint.corebankingservice.ObjectFactory.class,
    aminParsian.webService.AchAmin.com.caspian.channelmanager.core.webservicegateway.service.ObjectFactory.class,
//    aminParsian.webService.AchAmin.com.caspian.moderngateway.core.webservicegateway.endpoint.internalbankservice.ObjectFactory.class,//AchAmin.com.caspian.moderngateway.core.webservicegateway.endpoint.//.ObjectFactory.class,
    aminParsian.webService.AchAmin.ir.parsian_bank.ObjectFactory.class
})
public interface ParsianBankSoap {


    /**
     * 
     * @param channelType
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.LoginResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/login")
    @WebResult(name = "loginResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.LoginResponse")
    public LoginResult login(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChUserInfoRequestBean request,
        @WebParam(name = "channelType", targetNamespace = "http://www.parsian-bank.ir/")
        ChannelServiceType channelType);

    /**
     * 
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.LoginAccountResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/loginAccount")
    @WebResult(name = "loginAccountResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "loginAccount", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.LoginAccount")
    @ResponseWrapper(localName = "loginAccountResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.LoginAccountResponse")
    public LoginAccountResult loginAccount(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChUserInfoRequestBean request);

    /**
     * 
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.LoginSwitchResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/loginSwitch")
    @WebResult(name = "loginSwitchResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "loginSwitch", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.LoginSwitch")
    @ResponseWrapper(localName = "loginSwitchResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.LoginSwitchResponse")
    public LoginSwitchResult loginSwitch(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChUserInfoRequestBean request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.parsian-bank.ir/checkLoginInternetBank")
    @WebResult(name = "checkLoginInternetBankResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "checkLoginInternetBank", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.CheckLoginInternetBank")
    @ResponseWrapper(localName = "checkLoginInternetBankResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.CheckLoginInternetBankResponse")
    public String checkLoginInternetBank(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChUserInfoRequestBean request);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.NormalTransferResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/normalTransfer")
    @WebResult(name = "normalTransferResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "normalTransfer", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.NormalTransfer")
    @ResponseWrapper(localName = "normalTransferResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.NormalTransferResponse")
    public NormalTransferResult normalTransfer(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChNormalTransferRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.AchNormalTransferResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/achNormalTransfer")
    @WebResult(name = "achNormalTransferResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "achNormalTransfer", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.AchNormalTransfer")
    @ResponseWrapper(localName = "achNormalTransferResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.AchNormalTransferResponse")
    public AchNormalTransferResult achNormalTransfer(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChAchNormalTransferRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param channelType
     * @param sessionId
     */
    @WebMethod(action = "http://www.parsian-bank.ir/logout")
    @RequestWrapper(localName = "logout", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.LogoutResponse")
    public void logout(
        @WebParam(name = "channelType", targetNamespace = "http://www.parsian-bank.ir/")
        ChannelServiceType channelType,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     */
    @WebMethod(action = "http://www.parsian-bank.ir/logoutAccount")
    @RequestWrapper(localName = "logoutAccount", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.LogoutAccount")
    @ResponseWrapper(localName = "logoutAccountResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.LogoutAccountResponse")
    public void logoutAccount(
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     */
    @WebMethod(action = "http://www.parsian-bank.ir/logoutSwitch")
    @RequestWrapper(localName = "logoutSwitch", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.LogoutSwitch")
    @ResponseWrapper(localName = "logoutSwitchResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.LogoutSwitchResponse")
    public void logoutSwitch(
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     */
    @WebMethod(action = "http://www.parsian-bank.ir/changePassword")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.ChangePasswordResponse")
    public void changePassword(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChChangePasswordRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.AchTransferReportResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/achTransferReport")
    @WebResult(name = "achTransferReportResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "achTransferReport", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.AchTransferReport")
    @ResponseWrapper(localName = "achTransferReportResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.AchTransferReportResponse")
    public AchTransferReportResult achTransferReport(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChAchTransferSearchRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.InstitutionalTransferResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/institutionalTransfer")
    @WebResult(name = "institutionalTransferResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "institutionalTransfer", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.InstitutionalTransfer")
    @ResponseWrapper(localName = "institutionalTransferResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.InstitutionalTransferResponse")
    public InstitutionalTransferResult institutionalTransfer(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChInstitutionalTransferRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.GetPaymentBillStatementResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/getPaymentBillStatement")
    @WebResult(name = "getPaymentBillStatementResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "getPaymentBillStatement", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetPaymentBillStatement")
    @ResponseWrapper(localName = "getPaymentBillStatementResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetPaymentBillStatementResponse")
    public GetPaymentBillStatementResult getPaymentBillStatement(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChPaymentBillStatementRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.GetStatementResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/getStatement")
    @WebResult(name = "getStatementResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "getStatement", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetStatement")
    @ResponseWrapper(localName = "getStatementResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetStatementResponse")
    public GetStatementResult getStatement(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChStatementSearchRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.AchTransactionReportResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/achTransactionReport")
    @WebResult(name = "achTransactionReportResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "achTransactionReport", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.AchTransactionReport")
    @ResponseWrapper(localName = "achTransactionReportResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.AchTransactionReportResponse")
    public AchTransactionReportResult achTransactionReport(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChAchTransactionSearchRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.GetDepositsResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/getDeposits")
    @WebResult(name = "getDepositsResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "getDeposits", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetDeposits")
    @ResponseWrapper(localName = "getDepositsResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetDepositsResponse")
    public GetDepositsResult getDeposits(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChDepositSearchRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.RtgsNormalTransferResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/rtgsNormalTransfer")
    @WebResult(name = "rtgsNormalTransferResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "rtgsNormalTransfer", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.RtgsNormalTransfer")
    @ResponseWrapper(localName = "rtgsNormalTransferResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.RtgsNormalTransferResponse")
    public RtgsNormalTransferResult rtgsNormalTransfer(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChRtgsNormalTransferRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.RtgsTransferReportResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/rtgsTransferReport")
    @WebResult(name = "rtgsTransferReportResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "rtgsTransferReport", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.RtgsTransferReport")
    @ResponseWrapper(localName = "rtgsTransferReportResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.RtgsTransferReportResponse")
    public RtgsTransferReportResult rtgsTransferReport(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChRtgTransferSearchRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.ConvertIbanToDepositNumberResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/convertIbanToDepositNumber")
    @WebResult(name = "convertIbanToDepositNumberResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "convertIbanToDepositNumber", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.ConvertIbanToDepositNumber")
    @ResponseWrapper(localName = "convertIbanToDepositNumberResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.ConvertIbanToDepositNumberResponse")
    public ConvertIbanToDepositNumberResult convertIbanToDepositNumber(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChIbanToDepositRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.GetCardOwnerResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/getCardOwner")
    @WebResult(name = "getCardOwnerResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "getCardOwner", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetCardOwner")
    @ResponseWrapper(localName = "getCardOwnerResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetCardOwnerResponse")
    public GetCardOwnerResult getCardOwner(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChCardOwnerRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.CardTransferResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/cardTransfer")
    @WebResult(name = "cardTransferResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "cardTransfer", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.CardTransfer")
    @ResponseWrapper(localName = "cardTransferResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.CardTransferResponse")
    public CardTransferResult cardTransfer(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChFundTransferRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.BatchTransferResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/batchTransfer")
    @WebResult(name = "batchTransferResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "batchTransfer", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.BatchTransfer")
    @ResponseWrapper(localName = "batchTransferResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.BatchTransferResponse")
    public BatchTransferResult batchTransfer(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChBatchTransferRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.AchBatchTransferResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/achBatchTransfer")
    @WebResult(name = "achBatchTransferResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "achBatchTransfer", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.AchBatchTransfer")
    @ResponseWrapper(localName = "achBatchTransferResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.AchBatchTransferResponse")
    public AchBatchTransferResult achBatchTransfer(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChBatchAchTransferRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.AcntTransferResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/normalAcntTransfer")
    @WebResult(name = "normalAcntTransferResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "normalAcntTransfer", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.NormalAcntTransfer")
    @ResponseWrapper(localName = "normalAcntTransferResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.NormalAcntTransferResponse")
    public AcntTransferResult normalAcntTransfer(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        NormalAcntTransferRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.AcntTransferResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/batchAcntTransfer")
    @WebResult(name = "batchAcntTransferResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "batchAcntTransfer", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.BatchAcntTransfer")
    @ResponseWrapper(localName = "batchAcntTransferResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.BatchAcntTransferResponse")
    public AcntTransferResult batchAcntTransfer(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        BatchAcntTransferRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.GetDepositOwnerNameResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/getDepositOwnerName")
    @WebResult(name = "getDepositOwnerNameResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "getDepositOwnerName", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetDepositOwnerName")
    @ResponseWrapper(localName = "getDepositOwnerNameResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetDepositOwnerNameResponse")
    public GetDepositOwnerNameResult getDepositOwnerName(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChDepositOwnerRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.CardBalanceInquiryResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/cardBalanceInquiry")
    @WebResult(name = "cardBalanceInquiryResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "cardBalanceInquiry", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.CardBalanceInquiry")
    @ResponseWrapper(localName = "cardBalanceInquiryResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.CardBalanceInquiryResponse")
    public CardBalanceInquiryResult cardBalanceInquiry(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChCardBalanceRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.CardBalanceInquiryWithCustIdResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/cardBalanceInquiryWithCustId")
    @WebResult(name = "cardBalanceInquiryWithCustIdResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "cardBalanceInquiryWithCustId", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.CardBalanceInquiryWithCustId")
    @ResponseWrapper(localName = "cardBalanceInquiryWithCustIdResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.CardBalanceInquiryWithCustIdResponse")
    public CardBalanceInquiryWithCustIdResult cardBalanceInquiryWithCustId(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChCardBalanceRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.GetCardDepositsResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/getCardDeposits")
    @WebResult(name = "getCardDepositsResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "getCardDeposits", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetCardDeposits")
    @ResponseWrapper(localName = "getCardDepositsResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetCardDepositsResponse")
    public GetCardDepositsResult getCardDeposits(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChCardDepositRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.PayLoanResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/payLoan")
    @WebResult(name = "payLoanResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "payLoan", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.PayLoan")
    @ResponseWrapper(localName = "payLoanResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.PayLoanResponse")
    public PayLoanResult payLoan(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChLoanPaymentRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.GetChequeBookListResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/getChequeBookList")
    @WebResult(name = "getChequeBookListResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "getChequeBookList", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetChequeBookList")
    @ResponseWrapper(localName = "getChequeBookListResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetChequeBookListResponse")
    public GetChequeBookListResult getChequeBookList(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChBaseSearchChequeBookRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.GetChequeResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/getCheque")
    @WebResult(name = "getChequeResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "getCheque", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetCheque")
    @ResponseWrapper(localName = "getChequeResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetChequeResponse")
    public GetChequeResult getCheque(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChChequeSearchRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.DoPaymentResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/doPayment")
    @WebResult(name = "doPaymentResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "doPayment", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.DoPayment")
    @ResponseWrapper(localName = "doPaymentResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.DoPaymentResponse")
    public DoPaymentResult doPayment(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChPaymentRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.PayBillResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/payBill")
    @WebResult(name = "payBillResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "payBill", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.PayBill")
    @ResponseWrapper(localName = "payBillResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.PayBillResponse")
    public PayBillResult payBill(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChBillPaymentRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.GetCardStatementInquiryResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/getCardStatementInquiry")
    @WebResult(name = "getCardStatementInquiryResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "getCardStatementInquiry", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetCardStatementInquiry")
    @ResponseWrapper(localName = "getCardStatementInquiryResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetCardStatementInquiryResponse")
    public GetCardStatementInquiryResult getCardStatementInquiry(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChCardStatementRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.SwitchFundTransferFromPhysicalTerminalResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/switchFundTransferFromPhysicalTerminal")
    @WebResult(name = "switchFundTransferFromPhysicalTerminalResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "switchFundTransferFromPhysicalTerminal", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.SwitchFundTransferFromPhysicalTerminal")
    @ResponseWrapper(localName = "switchFundTransferFromPhysicalTerminalResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.SwitchFundTransferFromPhysicalTerminalResponse")
    public SwitchFundTransferFromPhysicalTerminalResult switchFundTransferFromPhysicalTerminal(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChPhysicalCardTransferRequest request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.GetDestinationCardOwnerResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/getDestinationCardOwner")
    @WebResult(name = "getDestinationCardOwnerResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "getDestinationCardOwner", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetDestinationCardOwner")
    @ResponseWrapper(localName = "getDestinationCardOwnerResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.GetDestinationCardOwnerResponse")
    public GetDestinationCardOwnerResult getDestinationCardOwner(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChDestinationCardOwnerRequest request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.InquiryTxnStatusResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/inquiryTxnStatus")
    @WebResult(name = "inquiryTxnStatusResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "inquiryTxnStatus", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.InquiryTxnStatus")
    @ResponseWrapper(localName = "inquiryTxnStatusResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.InquiryTxnStatusResponse")
    public InquiryTxnStatusResult inquiryTxnStatus(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        String request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param request
     * @return
     *     returns aminParsian.webService.AchAmin.ir.parsian_bank.ConvertDepositNumberToIbanResult
     */
    @WebMethod(action = "http://www.parsian-bank.ir/convertDepositNumberToIban")
    @WebResult(name = "convertDepositNumberToIbanResult", targetNamespace = "http://www.parsian-bank.ir/")
    @RequestWrapper(localName = "convertDepositNumberToIban", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.ConvertDepositNumberToIban")
    @ResponseWrapper(localName = "convertDepositNumberToIbanResponse", targetNamespace = "http://www.parsian-bank.ir/", className = "aminParsian.webService.AchAmin.ir.parsian_bank.ConvertDepositNumberToIbanResponse")
    public ConvertDepositNumberToIbanResult convertDepositNumberToIban(
        @WebParam(name = "request", targetNamespace = "http://www.parsian-bank.ir/")
        ChDepositNumberToIbanRequestBean request,
        @WebParam(name = "sessionId", targetNamespace = "http://www.parsian-bank.ir/")
        String sessionId);

}
