
package aminParsian.webService.AchAmin.ir.parsian_bank;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ParsianBank", targetNamespace = "http://www.parsian-bank.ir/", wsdlLocation = "file:/C:/Ach/src/aminParsian/webService/AchAmin/a.wsdl")
public class ParsianBank
    extends Service
{

    private final static URL PARSIANBANK_WSDL_LOCATION;
    private final static WebServiceException PARSIANBANK_EXCEPTION;
    private final static QName PARSIANBANK_QNAME = new QName("http://www.parsian-bank.ir/", "ParsianBank");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/tomcat/webapps/ROOT/WEB-INF/classes/aminParsian/webService/AchAmin/a.wsdl");
//            url = new URL("file:/E:/work/amin parsian/Ach/a.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARSIANBANK_WSDL_LOCATION = url;
        PARSIANBANK_EXCEPTION = e;
    }

    public ParsianBank() {
        super(__getWsdlLocation(), PARSIANBANK_QNAME);
    }

    public ParsianBank(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARSIANBANK_QNAME, features);
    }

    public ParsianBank(URL wsdlLocation) {
        super(wsdlLocation, PARSIANBANK_QNAME);
    }

    public ParsianBank(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARSIANBANK_QNAME, features);
    }

    public ParsianBank(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ParsianBank(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ParsianBankSoap
     */
    @WebEndpoint(name = "ParsianBankSoap")
    public ParsianBankSoap getParsianBankSoap() {
        return super.getPort(new QName("http://www.parsian-bank.ir/", "ParsianBankSoap"), ParsianBankSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ParsianBankSoap
     */
    @WebEndpoint(name = "ParsianBankSoap")
    public ParsianBankSoap getParsianBankSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.parsian-bank.ir/", "ParsianBankSoap"), ParsianBankSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARSIANBANK_EXCEPTION!= null) {
            throw PARSIANBANK_EXCEPTION;
        }
        return PARSIANBANK_WSDL_LOCATION;
    }

}
