
package aminParsian.webService.EstelamHoviayat;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SabtInq", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://reinsure.centinsur.ir/Sabtv2out?wsdl")
public class SabtInq
    extends Service
{

    private final static URL SABTINQ_WSDL_LOCATION;
    private final static WebServiceException SABTINQ_EXCEPTION;
    private final static QName SABTINQ_QNAME = new QName("http://tempuri.org/", "SabtInq");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://reinsure.centinsur.ir/Sabtv2out?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SABTINQ_WSDL_LOCATION = url;
        SABTINQ_EXCEPTION = e;
    }

    public SabtInq() {
        super(__getWsdlLocation(), SABTINQ_QNAME);
    }

    public SabtInq(WebServiceFeature... features) {
        super(__getWsdlLocation(), SABTINQ_QNAME, features);
    }

    public SabtInq(URL wsdlLocation) {
        super(wsdlLocation, SABTINQ_QNAME);
    }

    public SabtInq(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SABTINQ_QNAME, features);
    }

    public SabtInq(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SabtInq(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISabtInq
     */
    @WebEndpoint(name = "myBasicHttpBinding_ISabtInq")
    public ISabtInq getMyBasicHttpBindingISabtInq() {
        return super.getPort(new QName("http://tempuri.org/", "myBasicHttpBinding_ISabtInq"), ISabtInq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISabtInq
     */
    @WebEndpoint(name = "myBasicHttpBinding_ISabtInq")
    public ISabtInq getMyBasicHttpBindingISabtInq(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "myBasicHttpBinding_ISabtInq"), ISabtInq.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SABTINQ_EXCEPTION!= null) {
            throw SABTINQ_EXCEPTION;
        }
        return SABTINQ_WSDL_LOCATION;
    }

}
